name: Build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for SonarQube

      - name: Debug working directory
        run: pwd

      - name: List project files
        run: ls -R

      - name: Install dependencies
        run: npm install
        working-directory: front-end  # Adjust this if needed

      - name: Run unit tests with coverage
        run: npm run coverage
        working-directory: front-end  # Adjust this if needed

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=front-end/src
            -Dsonar.tests=front-end/coverage
            -Dsonar.javascript.lcov.reportPath=front-end/coverage/lcov.info
